# fly.toml app configuration file generated for mautic on 2024-01-09T12:50:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mautic"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "atl"

[build]
  image = "mautic/mautic:v4-apache"

[mounts]
  source="mauticdata"
  destination="/var/www/html"

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 50
    type = "connections"
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "30s"
    restart_limit = 1
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

